org: shalev396

app: woltflow

service: woltflow-server

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs20.x
  timeout: 30
  memorySize: 1024
  region: il-central-1
  apiGateway:
    shouldStartNameWithService: true
  logs:
    restApi: false
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    DATABASE_URL_DEV: ${env:DATABASE_URL_DEV}
    ENV: Production
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    OAUTH_REDIRECT_URI: ${env:OAUTH_REDIRECT_URI}
    OAUTH_REDIRECT_URI_DEV: ${env:OAUTH_REDIRECT_URI_DEV}
    JWT_SECRET: ${env:JWT_SECRET}
    DEVELOPMENT_DATE: ${env:DEVELOPMENT_DATE, ""}
    AWS_ACCESS_CONNECT_KEY: ${env:AWS_ACCESS_CONNECT_KEY}
    AWS_ACCESS_SECRET: ${env:AWS_ACCESS_SECRET}
    AWS_REGIONS: ${env:AWS_REGIONS}
    ASSETS_BUCKET_NAME: ${env:ASSETS_BUCKET_NAME}
    REFRESH_TOKENS_FUNCTION_NAME: ${self:service}-${self:provider.stage, 'dev'}-refreshTokens
    WOLT_BUY_GIFT_FUNCTION_NAME: ${self:service}-${self:provider.stage, 'dev'}-woltBuyGift
    GET_DAILY_CODE_FUNCTION_NAME: ${self:service}-${self:provider.stage, 'dev'}-getDailyCode
    WOLT_APPLY_GIFT_FUNCTION_NAME: ${self:service}-${self:provider.stage, 'dev'}-woltApplyGift

  ecr:
    images:
      woltflow-selenium-image:
        path: ./
        file: Dockerfile
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage, 'dev'}-refreshTokens
            - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage, 'dev'}-woltBuyGift
            - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage, 'dev'}-getDailyCode
            - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage, 'dev'}-woltApplyGift
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "arn:aws:s3:::${env:ASSETS_BUCKET_NAME}/*"
        - Effect: Allow
          Action: ecr:GetAuthorizationToken
          Resource: "*"
        - Effect: Allow
          Action:
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - ecr:InitiateLayerUpload
            - ecr:UploadLayerPart
            - ecr:CompleteLayerUpload
            - ecr:PutImage
          Resource: "*"
package:
  # individually: true
  excludeDevDependencies: true
  patterns:
    - "!src/**"
    # - "!node_modules/**"
    # - "node_modules/pg/**"
    - "!.serverless/**"
    - "!.webpack/**"
    - "!.build/**"
    - "!tsconfig.json"
    - "!*.md"
    - "!screenshots/**"
    - "!layers/**"
    - "!undefined/**"
    - "!*.zip"
    - "!webpack.config.js"
    - "dist/**"
    - "package.json"
    - "node_modules/**"

build:
  esbuild: false # Disable built-in ESBuild support
plugins:
  - serverless-offline

custom:
  serverless-offline:
    # host: 127.0.0.1 # ← Force Hapi to bind here instead of 'localhost'
    httpPort: 3000
    lambdaPort: 3002
    noPrependStageInUrl: true
    reloadHandler: true
    disableCookieValidation: true # ← Disables strictHeader cookie validation in Hapi
    enforceSecureCookies: false # ← Ensures Hapi won't require HTTPS for cookies
    printOutput: true
  dotenv:
    path: ./.env

functions:
  #auth
  authMe:
    handler: ./dist/handlers/auth/authMeHandler.handler
    events:
      - httpApi:
          path: /api/auth/me
          method: get

  logout:
    handler: ./dist/handlers/auth/logout.handler
    events:
      - httpApi:
          path: /api/auth/logout
          method: post

  oauthCallback:
    handler: ./dist/handlers/auth/oauthCallback.handler
    events:
      - httpApi:
          path: /api/oauth2/callback
          method: get

  oauthStart:
    handler: ./dist/handlers/auth/oauthStart.handler
    events:
      - httpApi:
          path: /api/oauth2/start
          method: get

  # automation no selenium
  refreshTokens:
    handler: ./dist/handlers/automation/refreshTokens.handler
    events:
      - httpApi:
          path: /api/wolt/refreshTokens
          method: get

  startAllRuns:
    handler: ./dist/handlers/automation/startAllRuns.handler
    events:
      - httpApi:
          path: /api/automation/start-all-runs
          method: get
      - schedule:
          rate: cron(0 10 ? * SUN,MON,TUE,WED,THU *)
          description: "Trigger startAllRuns on weekdays at 10:00 UTC (12:00 Israel time)"

  # gmail

  getDailyCode:
    handler: ./dist/handlers/gmail/getDailyCode.handler
    events:
      - httpApi:
          path: /api/gmail/daily-code
          method: get
  #runs
  getUserRuns:
    handler: ./dist/handlers/runs/getUserRuns.handler
    events:
      - httpApi:
          path: /api/runs
          method: get
  #setting
  getUserSettings:
    handler: ./dist/handlers/setting/getusersettings.handler
    events:
      - httpApi:
          path: /api/setting
          method: get

  setUserSettings:
    handler: ./dist/handlers/setting/setusersettings.handler
    events:
      - httpApi:
          path: /api/setting
          method: post

  #automation with selenium
  woltBuyGift:
    image:
      name: woltflow-selenium-image
      command: ["dist/handlers/automation/woltBuyGift.handler"]
    memorySize: 1536
    ephemeralStorageSize: 1536
    timeout: 200
    # events:
    #   - httpApi:
    #       path: /api/wolt/buyGift
    #       method: get

  woltApplyGift:
    image:
      name: woltflow-selenium-image
      command: ["dist/handlers/automation/woltApplyGift.handler"]
    memorySize: 1536
    ephemeralStorageSize: 1536
    timeout: 60
    events:
      - httpApi:
          path: /api/wolt/applyGift
          method: get
