org: shalev396

app: woltflow

service: woltflow-server

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  memorySize: 1024
  region: eu-central-1
  apiGateway:
    shouldStartNameWithService: true
  logs:
    restApi: false
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    DATABASE_URL_DEV: ${env:DATABASE_URL_DEV}
    ENV: ${env:ENV}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    OAUTH_REDIRECT_URI: ${env:OAUTH_REDIRECT_URI}
    OAUTH_REDIRECT_URI_DEV: ${env:OAUTH_REDIRECT_URI_DEV}
    JWT_SECRET: ${env:JWT_SECRET}
    IS_OFFLINE: ${env:IS_OFFLINE, "false"}
    DEVELOPMENT_DATE: ${env:DEVELOPMENT_DATE, ""}
    AWS_ACCESS_CONNECT_KEY: ${env:AWS_ACCESS_CONNECT_KEY}
    AWS_ACCESS_SECRET: ${env:AWS_ACCESS_SECRET}
    AWS_REGIONS: ${env:AWS_REGIONS}
    ASSETS_BUCKET_NAME: ${env:ASSETS_BUCKET_NAME}
    REFRESH_TOKENS_FUNCTION_NAME: ${self:service}-${self:provider.stage, 'dev'}-refreshTokens
    WOLT_BUY_GIFT_FUNCTION_NAME: ${self:service}-${self:provider.stage, 'dev'}-woltBuyGift
    GET_DAILY_CODE_FUNCTION_NAME: ${self:service}-${self:provider.stage, 'dev'}-getDailyCode
    WOLT_APPLY_GIFT_FUNCTION_NAME: ${self:service}-${self:provider.stage, 'dev'}-woltApplyGift
    PATH: "/opt/bin:${env:PATH, ''}"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage, 'dev'}-refreshTokens
            - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage, 'dev'}-woltBuyGift
            - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage, 'dev'}-getDailyCode
            - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage, 'dev'}-woltApplyGift
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "arn:aws:s3:::${env:ASSETS_BUCKET_NAME}/*"

package:
  individually: true
  excludeDevDependencies: true # true
  patterns:
    - "!src/**"
    # - "!node_modules/**"
    - "!.serverless/**"
    - "!.build/**"
    - "!tsconfig.json"
    - "!*.md"
    - "!screenshots/**"
    - "!layers/**"
    - "!undefined/**"
    - "!*.zip"
    - "dist/**"
    - "package.json"

build:
  esbuild:
    false
    # Disable built-in ESBuild support
plugins:
  - serverless-offline
  - serverless-webpack
  # - serverless-dotenv-plugin

useDotenv: true

custom:
  serverless-offline:
    # host: 127.0.0.1 # ← Force Hapi to bind here instead of 'localhost'
    httpPort: 3000
    lambdaPort: 3002
    noPrependStageInUrl: true
    reloadHandler: true
    disableCookieValidation: true # ← Disables strictHeader cookie validation in Hapi
    enforceSecureCookies: false # ← Ensures Hapi won't require HTTPS for cookies
    printOutput: true
  hooks:
    before:offline:start: npm run build
    before:deploy:deploy: npm run build
    package:initialize: npm run build
  dotenv:
    path: ./.env
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules:
      forceInclude:
        - pg
        - pg-hstore
        - aws-sdk

layers:
  chromedriver:
    path: layers/chromedriver-layer
    name: ${sls:stage}-chromedriver-layer
    description: ChromeDriver layer for Selenium automation
    compatibleRuntimes:
      - nodejs20.x
    compatibleArchitectures:
      - x86_64

  chrome:
    path: layers/chrome-layer
    name: ${sls:stage}-chrome-layer
    description: Headless Chrome layer for Selenium automation
    compatibleRuntimes:
      - nodejs20.x
    compatibleArchitectures:
      - x86_64

functions:
  oauthStart:
    handler: ./dist/handlers/auth/oauthStart.handler
    events:
      - httpApi:
          path: /api/oauth2/start
          method: get

  oauthCallback:
    handler: ./dist/handlers/auth/oauthCallback.handler
    events:
      - httpApi:
          path: /api/oauth2/callback
          method: get

  authMe:
    handler: ./dist/handlers/auth/authMeHandler.handler
    events:
      - httpApi:
          path: /api/auth/me
          method: get

  logout:
    handler: ./dist/handlers/auth/logout.handler
    events:
      - httpApi:
          path: /api/auth/logout
          method: post

  getDailyCode:
    handler: ./dist/handlers/gmail/getDailyCode.handler
    events:
      - httpApi:
          path: /api/gmail/daily-code
          method: get

  getUserSettings:
    handler: ./dist/handlers/setting/getusersettings.handler
    events:
      - httpApi:
          path: /api/setting
          method: get

  setUserSettings:
    handler: ./dist/handlers/setting/setusersettings.handler
    events:
      - httpApi:
          path: /api/setting
          method: post

  startAllRuns:
    handler: ./dist/handlers/automation/startAllRuns.handler
    events:
      - httpApi:
          path: /api/automation/start-all-runs
          method: get
      - schedule:
          rate: cron(0 10 ? * SUN,MON,TUE,WED,THU *)
          description: "Trigger startAllRuns on weekdays at 10:00 UTC (12:00 Israel time)"

  refreshTokens:
    handler: ./dist/handlers/automation/refreshTokens.handler
    events:
      - httpApi:
          path: /api/wolt/refreshTokens
          method: get

  woltBuyGift:
    handler: ./dist/handlers/automation/woltBuyGift.handler
    layers:
      - !Ref ChromedriverLambdaLayer
      - !Ref ChromeLambdaLayer
    memorySize: 1024
    timeout: 70
    events:
      - httpApi:
          path: /api/wolt/buyGift
          method: get

  woltApplyGift:
    handler: ./dist/handlers/automation/woltApplyGift.handler
    layers:
      - !Ref ChromedriverLambdaLayer
      - !Ref ChromeLambdaLayer
    memorySize: 1024
    timeout: 60
    events:
      - httpApi:
          path: /api/wolt/applyGift
          method: get

  getUserRuns:
    handler: ./dist/handlers/runs/getUserRuns.handler
    events:
      - httpApi:
          path: /api/runs
          method: get
