# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: shalev396
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: woltflow
# "service" is the name of this project. This will also be added to your AWS resource names.
service: WoltFlow

provider:
  name: aws
  runtime: python3.12

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: rate(1 minute)
