name: Backend CI/CD

permissions:
  id-token: write
  contents: read



on:
  push:
    branches:
      - "main" # Production deployment
      - "dev" # Development deployment
    paths:
      - "Server/**"
      - ".github/workflows/Backend-CICD.yml"

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Load environment variables from ENV
        if: github.ref == 'refs/heads/main'
        run: |
          echo '${{ secrets.ENV }}' > .env
        working-directory: Server

      - name: Export .env variables
        uses: falti/dotenv-action@v1.1.4
        with:
          path: Server/.env
          export-variables: true
          keys-case: bypass

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGIONS }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/my-github-actions-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install dependencies
        run: npm ci
        working-directory: Server

      - name: Build TypeScript
        run: npm run build
        working-directory: Server

      - name: Deploy to dev stage
        if: github.ref == 'refs/heads/dev'
        run: npm run deploy:dev
        working-directory: Server

      - name: Deploy to prod stage
        if: github.ref == 'refs/heads/main'
        run: npm run deploy:prod
        working-directory: Server
