name: Frontend CI/CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - "main" # Production deployment
      - "dev" # Development deployment
    paths:
      - "Client/**"
      - ".github/workflows/Frontend-CICD.yml"

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Load environment variables for dev
        if: github.ref == 'refs/heads/dev'
        run: |
          echo '${{ secrets.ENV_DEV }}' > .env.dev
        working-directory: Server

      - name: Load environment variables for prod
        if: github.ref == 'refs/heads/main'
        run: |
          echo '${{ secrets.ENV_PROD }}' > .env.prod
        working-directory: Server

      - name: Export .env.dev variables
        if: github.ref == 'refs/heads/dev'
        uses: falti/dotenv-action@v1.1.4
        with:
          path: Server/.env.dev
          export-variables: true
          keys-case: bypass
          mask-variables: true

      - name: Export .env.prod variables
        if: github.ref == 'refs/heads/main'
        uses: falti/dotenv-action@v1.1.4
        with:
          path: Server/.env.prod
          export-variables: true
          keys-case: bypass
          mask-variables: true

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: Client

      - name: Build
        run: npm run build
        working-directory: Client

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/my-github-actions-role

      - name: Get CloudFront Distribution ID
        id: get-cf-id
        run: |
          STACK_NAME="woltflow-server-dev"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            STACK_NAME="woltflow-server-prod"
          fi
          CF_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
          echo "distribution_id=$CF_ID" >> $GITHUB_OUTPUT
          echo "Found CloudFront Distribution ID: $CF_ID"

      - name: Deploy to S3 (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          aws s3 sync ./Client/dist s3://${{ env.S3_CLIENT_BUCKET_NAME }}/ --delete

      - name: Deploy to S3 (prod)
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync ./Client/dist s3://${{ env.S3_CLIENT_BUCKET_NAME }}/ --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ steps.get-cf-id.outputs.distribution_id }} --paths "/*"
