name: Frontend CI/CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - "main" # Production
      - "dev" # Development
      - "qa" # QA
    paths:
      - "Client/**"
      - ".github/workflows/Frontend-CICD.yml"

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'dev' && 'dev' || github.ref_name == 'qa' && 'qa' }}

    env:
      # Non-sensitive configuration from environment variables
      ## Global repository variables
      AWS_REGION: ${{ vars.AWS_REGION }}
      ## Per environment variables
      VITE_SMS_ENABLED: ${{ vars.ENABLED_SMS }}
      # Sensitive data from secrets (automatically masked in logs)
      ## Global repository secrets
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      STACK_BASE_NAME: ${{ secrets.STACK_BASE_NAME }}
      ## Per environment secrets
      VITE_GOOGLE_ANALYTICS_ID: ${{secrets.VITE_GOOGLE_ANALYTICS_ID}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set stage
        id: stage
        run: echo "name=${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'dev' && 'dev' || github.ref_name == 'qa' && 'qa' }}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: Client

      - name: Build
        run: npm run build
        working-directory: Client

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/my-github-actions-role

      - name: Get CloudFormation Outputs
        id: cf
        run: |
          STACK="${{ env.STACK_BASE_NAME }}-${{ steps.stage.outputs.name }}"
          CF_ID=$(aws cloudformation describe-stacks --stack-name "$STACK" --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
          S3_BUCKET=$(aws cloudformation describe-stacks --stack-name "$STACK" --query "Stacks[0].Outputs[?OutputKey=='S3ClientBucketName'].OutputValue" --output text)
          echo "cf_id=$CF_ID" >> $GITHUB_OUTPUT
          echo "s3_bucket=$S3_BUCKET" >> $GITHUB_OUTPUT

      - name: Deploy to S3
        run: aws s3 sync ./Client/dist s3://${{ steps.cf.outputs.s3_bucket }}/ --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ steps.cf.outputs.cf_id }} --paths "/*"
