name: Prod CI/CD Frontend
on:
  push:
    branches:
      - "main"
    paths:
      - "Client/**"
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Load environment variables from PROD_ENV
        run: |
          echo '${{ secrets.PROD_ENV }}' > .env
        working-directory: Client

      - name: Export .env variables
        uses: falti/dotenv-action@v1.1.4
        with:
          path: Client/.env
          export-variables: true
          keys-case: bypass

      - name: Install dependencies
        run: npm install --legacy-peer-deps --prefix Client

      - name: Build
        run: npm run build --prefix Client

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_CONNECT_KEY }}
          aws-secret-access-key: ${{ env.AWS_ACCESS_SECRET }}
          aws-region: eu-central-1

      - name: Deploy with AWS CLI
        run: |
          aws s3 sync ./Client/dist s3://${{ env.S3_BUCKET_NAME }}/
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
