# name: Prod CI/CD Backend

# on:
#   push:
#     branches:
#       - main # Adjust if your default branch is named differently
#     paths:
#       - "Server/**"

# permissions:
#   contents: read

# jobs:
#   deploy-backend:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Set Up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20 # Adjust based on your project's requirements

#       - name: Load environment variables from PROD_ENV
#         run: |
#           echo '${{ secrets.PROD_ENV }}' > .env
#         working-directory: Server

#       - name: Export .env variables
#         uses: falti/dotenv-action@v1.1.4
#         with:
#           path: Server/.env
#           export-variables: true
#           keys-case: bypass

#       - name: Install Dependencies
#         run: npm install --prefix Server

#       - name: Build
#         run: npm run build --prefix Server

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ env.AWS_ACCESS_CONNECT_KEY }}
#           aws-secret-access-key: ${{ env.AWS_ACCESS_SECRET }}
#           aws-region: us-east-1

#       - name: Deploy with Serverless Framework
#         uses: serverless/github-action@v4
#         with:
#           args: deploy --config Server/serverless.yml
#         env:
#           # SERVERLESS_ACCESS_KEY: ${{ env.SERVERLESS_ACCESS_KEY }}
#           # Alternatively, if not using SERVERLESS_ACCESS_KEY:
#           # AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_CONNECT_KEY }}
#           # AWS_SECRET_ACCESS_KEY: ${{ env.AWS_ACCESS_SECRET }}
#           SERVERLESS_ACCESS_KEY: ${{ env.SLS_ACCESS_KEY }}
